apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: api-gateway
  labels:
    app: grafana
    project: api-rate-limiter
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-service:9090
        access: proxy
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "15s"
          httpMethod: POST
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provisioning
  namespace: api-gateway
  labels:
    app: grafana
    project: api-rate-limiter
data:
  dashboard-provisioning.yaml: |
    apiVersion: 1
    providers:
      - name: "api-gateway-dashboards"
        orgId: 1
        folder: "API Gateway"
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards